"""Is a pinned package the PUBLISHED artifact, or was it edited in place?

Lives beside `code_snapshot.py` on purpose: that module writes the `framework`
code record and the FRAMEWORK_BLIND_SPOT warning that goes with it, and this is
the check that closes the warning. Both `/discover` (verify-framework) and
`/repro` (the code axis) read it, which is what makes it shared rather than
either one's.
"""
import json
import os
import subprocess
import sys



#
# `code_source.source: framework` records `<pkg>==<version>` instead of a commit,
# and `code_snapshot.py` has always warned that this "CANNOT see a local edit to the
# installed package, where a tree would have produced a dirty patch". That sentence
# was written as a permanent limitation. It is not one.
#
# pip writes `<dist-info>/RECORD` at install time: one row per installed file, with
# a sha256. Hashing the files on disk and comparing against it detects any edit made
# after the install — offline, no network, no wheel to re-download. So the question
# "is this package the published artifact, or did somebody patch it in place" has a
# real answer, and a warning string was standing where an answer could go.
#
# The distinction is not academic on the project this was built for: the deployed
# model's `train_args.optimizer` is `MuSGD`, and whether that is stock in the pinned
# version or a local patch is the difference between a reproducible recipe and one
# that only ever worked on one machine.
#
# It runs in the TARGET interpreter, not MLClaw's. The package lives in the run's
# environment, and asking MLClaw's own pixi env about it answers a question about the
# wrong world — the same rule `/eval-init` Step 1 states for resolving a framework
# version. The snippet is therefore stdlib-only: nothing may be installed into an
# environment being audited.

_INTEGRITY_SNIPPET = r'''
import base64, hashlib, json, os, sys
try:
    from importlib import metadata as md
except Exception as exc:
    print(json.dumps({"state": "unverifiable",
                      "detail": "no importlib.metadata: %s" % exc})); raise SystemExit
name = sys.argv[1]
try:
    dist = md.distribution(name)
except Exception:
    print(json.dumps({"state": "not_installed",
                      "detail": "%s is not installed in %s" % (name, sys.executable)}))
    raise SystemExit
installed = dist.version
try:
    rows = dist.read_text("RECORD")
except Exception:
    rows = None
if not rows:
    print(json.dumps({"state": "unverifiable", "installed_version": installed,
                      "detail": "no RECORD in the dist-info, so the install left "
                                "nothing to check against. Common for editable "
                                "installs and for packages placed by hand -- which "
                                "is itself worth knowing"}))
    raise SystemExit
base = str(dist.locate_file(""))
checked = mismatched = missing = skipped = 0
bad, gone = [], []
for line in rows.splitlines():
    if not line.strip():
        continue
    parts = line.rsplit(",", 2)
    if len(parts) != 3:
        continue
    rel, digest, _size = parts
    rel = rel.strip('"')
    if not digest.startswith("sha256="):
        skipped += 1          # RECORD itself, and .pyc rows pip leaves unhashed
        continue
    if rel.endswith(".pyc") or "__pycache__" in rel:
        skipped += 1          # regenerated by the interpreter; not the package
        continue
    path = os.path.join(base, rel)
    if not os.path.exists(path):
        missing += 1
        if len(gone) < 20:
            gone.append(rel)
        continue
    want = digest.split("=", 1)[1]
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    got = base64.urlsafe_b64encode(h.digest()).rstrip(b"=").decode()
    checked += 1
    if got != want:
        mismatched += 1
        if len(bad) < 20:
            bad.append(rel)
print(json.dumps({
    "state": ("edited" if mismatched else ("incomplete" if missing else "as_published")),
    "installed_version": installed, "files_checked": checked,
    "files_mismatched": mismatched, "files_missing": missing,
    "rows_skipped": skipped, "mismatched_sample": bad, "missing_sample": gone,
    "prefix": base}))
'''


# What each state MEANS, attached to the reading itself rather than to one
# caller's presentation. It lived in the CLI first, so `/repro`'s code axis got the
# bare state and had to re-explain it — and the one that most needs explaining is
# `not_installed`: absent from THIS interpreter says nothing about the package or
# about the environment that actually ran. That is the same unreachable/gone split
# the whole discovery engine turns on, and a meaning that only appears when a human
# runs the CLI is a meaning missing exactly where a record gets written.
STATE_MEANS = {
    "as_published": ("every hashed file matches the RECORD pip wrote at install "
                     "time -- this IS the published artifact, and the "
                     "`install <pkg>==<version>` contract reproduces it"),
    "edited": ("files differ from the RECORD pip wrote, so the installed package "
               "was modified AFTER install. `install <pkg>==<version>` will NOT "
               "reproduce what ran -- this is the blind spot, and it is real here. "
               "Capture the diff before that environment is rebuilt"),
    "incomplete": ("files the RECORD names are absent. A partial or hand-assembled "
                   "install, not an edit"),
    "not_installed": ("nothing to check in this interpreter. NOT a statement about "
                      "the package, and NOT a statement about the environment that "
                      "ran -- only about the one that was asked"),
    "unverifiable": "the check could not run; this is not a clean result",
    "no_interpreter": "the interpreter given is not executable on this machine",
    "usage": "the spec could not be parsed",
}


def framework_integrity(spec, python=None, budget_s=120.0):
    """-> dict. Is the installed package the published artifact?

    `state` is deliberately not one of the four lead statuses. This answers a
    question about a code source's IDENTITY, and its consumer is `/repro`'s code
    axis, which already has the right four words (`intact` / `drifted` / `gone` /
    `unverifiable`). Inventing a fifth lead status for it would put a
    same-spelling-opposite-bar word into the register, which is the defect this
    whole file is organised against.
    """
    name, sep, want = str(spec).partition("==")
    name = name.strip()
    if not name:
        return {"state": "usage", "detail": "no package name in %r" % spec, "means": STATE_MEANS["usage"]}
    interp = python or sys.executable
    try:
        p = subprocess.run([interp, "-c", _INTEGRITY_SNIPPET, name],
                           capture_output=True, text=True, encoding="utf-8", timeout=budget_s)
    except FileNotFoundError:
        return {"state": "no_interpreter", "means": STATE_MEANS["no_interpreter"],
                "detail": f"{interp} is not an executable on this machine"}
    except subprocess.TimeoutExpired:
        return {"state": "unverifiable", "means": STATE_MEANS["unverifiable"],
                "detail": f"hashing exceeded {budget_s:.0f}s -- NOT a mismatch"}
    except OSError as exc:
        return {"state": "unverifiable", "means": STATE_MEANS["unverifiable"],
                "detail": f"{type(exc).__name__}: {exc}"}
    try:
        res = json.loads((p.stdout or "").strip().splitlines()[-1])
    except Exception:
        return {"state": "unverifiable", "means": STATE_MEANS["unverifiable"],
                "detail": (f"the integrity snippet produced no JSON "
                           f"(exit {p.returncode}): "
                           f"{((p.stderr or p.stdout) or '').strip()[:300]}")}
    res["package"] = name
    res["interpreter"] = interp
    res["means"] = STATE_MEANS.get(res.get("state"))
    res["pinned_version"] = want if sep else None
    # The version question is separate from the integrity question and both can
    # fail. A record pinning 8.4.40 against an installed 8.4.41 is a different
    # problem from an edited 8.4.40, and collapsing them loses the fix.
    got = res.get("installed_version")
    if sep and got and got.split("+")[0] != want.split("+")[0]:
        res["version_matches_pin"] = False
    elif sep and got:
        res["version_matches_pin"] = True
    else:
        res["version_matches_pin"] = None
    return res


